title: Лаборатория медиакультуры и коммуникации журфак МГУ
description: Онлайн ресурс Лаборатории медиа, культуры и коммуникаций факультета журналистики Московского Государственного Университета.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
